"use strict";
const BASE="https://crebe-ucayali.github.io/banco-digital-accesible/lsp/";
const $=s=>document.querySelector(s);
const ui={entrada:$("#texto-senas"),generar:$("#generar"),limpiar:$("#limpiar"),descargar:$("#descargar"),estado:$("#estado"),resultado:$("#resultado"),texto:$("#texto-original"),ficha:$("#ficha")};
let banco=[],palabras=new Map(),letras=new Map();
const abc=new Set("abcdefghijklmnñopqrstuvwxyz".split(""));
function normalizar(t){return String(t||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zñ\s]/g," ").replace(/\s+/g," ").trim()}
function ruta(r){return /^https?:/i.test(r||"")?r:BASE+String(r||"").replace(/^\.\//,"")}
function esLetra(i){const p=normalizar(i.palabra);return p.length===1&&abc.has(p)}
function preparar(){banco.forEach(i=>{const p=normalizar(i.palabra);if(!p)return;if(!palabras.has(p))palabras.set(p,i);if(esLetra(i)&&!letras.has(p))letras.set(p,i)})}
function imagen(item,alt){const img=document.createElement("img");img.src=ruta(item.archivo_imagen);img.alt=alt;img.loading="eager";return img}
function sinImagen(l){const d=document.createElement("div");d.className="letra-no-disponible";d.innerHTML=`<span>${l.toUpperCase()}</span>`;d.setAttribute("aria-label",`Imagen dactilológica no disponible para la letra ${l}`);return d}
function deletreo(p){const c=document.createElement("div");c.className="deletreo";[...p].forEach(l=>{if(!abc.has(l))return;const t=document.createElement("div");t.className="letra-sena";const i=letras.get(l);t.appendChild(i?imagen(i,`Letra ${l.toUpperCase()} del alfabeto dactilológico peruano`):sinImagen(l));const r=document.createElement("strong");r.textContent=l;t.appendChild(r);c.appendChild(t)});return c}
function senaCompleta(p,i){const c=document.createElement("div");c.className="sena-completa";c.appendChild(imagen(i,`Representación visual de ${p} en Lengua de Señas Peruana`));const d=document.createElement("div");const x=document.createElement("p");x.textContent=i.descripcion||"Seña completa disponible en el banco visual.";d.appendChild(x);c.appendChild(d);return c}
function bloque(p){const a=document.createElement("article");a.className="bloque-palabra";const h=document.createElement("h3");h.textContent=p;a.appendChild(h);const i=palabras.get(p);a.appendChild(i&&!esLetra(i)?senaCompleta(p,i):deletreo(p));return a}
function generar(){const original=ui.entrada.value.trim(),limpio=normalizar(original);if(!limpio){ui.estado.className="estado error";ui.estado.textContent="Escribe un nombre o hasta tres palabras.";ui.entrada.focus();return}const lista=limpio.split(" ");if(lista.length>3){ui.estado.className="estado error";ui.estado.textContent="Puedes ingresar como máximo tres palabras, por ejemplo: nombre y dos apellidos.";ui.entrada.focus();return}ui.resultado.innerHTML="";ui.resultado.dataset.palabras=String(lista.length);lista.forEach(p=>ui.resultado.appendChild(bloque(p)));ui.texto.textContent=original;ui.descargar.disabled=false;ui.estado.className="estado exito";ui.estado.textContent="Recurso generado. Cada palabra ocupará una fila en el PDF."}
function limpiar(){ui.entrada.value="";ui.resultado.innerHTML='<p class="mensaje-vacio">Escribe un texto para generar el recurso.</p>';delete ui.resultado.dataset.palabras;ui.texto.textContent="Escribe un texto para generar el recurso.";ui.descargar.disabled=true;ui.estado.className="estado";ui.estado.textContent="Banco de señas preparado.";ui.entrada.focus()}
async function descargar(){if(!window.html2canvas||!window.jspdf){ui.estado.className="estado error";ui.estado.textContent="No se pudo cargar la función de PDF.";return}ui.descargar.disabled=true;ui.estado.textContent="Preparando el PDF horizontal…";ui.ficha.classList.add("exportacion-horizontal");try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const canvas=await window.html2canvas(ui.ficha,{scale:2,useCORS:true,backgroundColor:"#ffffff",width:ui.ficha.scrollWidth,height:ui.ficha.scrollHeight,windowWidth:ui.ficha.scrollWidth});const {jsPDF}=window.jspdf;const pdf=new jsPDF("l","mm","a4");const margen=8;const anchoPagina=pdf.internal.pageSize.getWidth();const altoPagina=pdf.internal.pageSize.getHeight();const anchoUtil=anchoPagina-(margen*2);const altoUtil=altoPagina-(margen*2);const escala=Math.min(anchoUtil/canvas.width,altoUtil/canvas.height);const anchoImagen=canvas.width*escala;const altoImagen=canvas.height*escala;const x=(anchoPagina-anchoImagen)/2;const y=(altoPagina-altoImagen)/2;const img=canvas.toDataURL("image/jpeg",.94);pdf.addImage(img,"JPEG",x,y,anchoImagen,altoImagen);const nombre=normalizar(ui.entrada.value).replace(/\s+/g,"-").slice(0,40)||"recurso-lsp";pdf.save(`${nombre}-lengua-de-senas-peruana.pdf`);ui.estado.className="estado exito";ui.estado.textContent="PDF descargado en una sola hoja horizontal."}catch(e){console.error(e);ui.estado.className="estado error";ui.estado.textContent="No fue posible generar el PDF."}finally{ui.ficha.classList.remove("exportacion-horizontal");ui.descargar.disabled=false}}
async function cargar(){try{const r=await fetch(BASE+"diccionario_lsp.json",{cache:"no-store"});if(!r.ok)throw new Error();banco=await r.json();preparar();ui.generar.disabled=false;ui.estado.className="estado exito";ui.estado.textContent="Banco de señas preparado. Puedes ingresar hasta tres palabras."}catch(e){console.error(e);ui.estado.className="estado error";ui.estado.textContent="No fue posible cargar el diccionario visual del Banco Digital Accesible."}}
ui.generar.addEventListener("click",generar);ui.limpiar.addEventListener("click",limpiar);ui.descargar.addEventListener("click",descargar);ui.entrada.addEventListener("keydown",e=>{if(e.key==="Enter")generar()});ui.resultado.innerHTML='<p class="mensaje-vacio">Escribe un texto para generar el recurso.</p>';ui.generar.disabled=true;cargar();